### ISSUE TITLE
Post rewrite hooks

### ISSUE THREAD

**Issue by leonardt** [leonardt/ast_tools#18]
In magma, we often do a final step after rewriting such as wrapping the rewritten function inside another function/object to implement some desired behavior.

For example, in combinational, we create a function call interface, so that
```
@comb
def f():
    ...
```
can be invoked as `f(inputs)`, but actually behaves as `f()(inputs)` (create magma circuit instance, wire up inputs, then return outputs).

Not sure what the best way to handle this given the new architecture is, perhaps a pass can define an "end hook" that is passed along and run during end_rewrite?

**Comment by leonardt** [comment]
I guess one option is that magma could implement this behavior in the rewritten AST (insert a wrapper function)

**Comment by cdonovick** [comment]
I'm not sure I understand the issue properly.  Would the following not work:
```
def caller(fn):
  def wrapped(*args, **kwargs)
    return fn()(*args, **kwargs)
  return wrapped

def comb(fn):
  return caller(_comb(fn)) # _comb being the main implementation 
```
end_rewrite returns a function so decorators should work normally.

Is it that you still want access to the metadata and env?

**Comment by cdonovick** [comment]
Also there is nothing special about the name `end_rewrite` if you need access to env and metadata when operating on the function/class (not the AST) the following should work.
```
class custom_end(end_rewrite):
  def rewrite(self, tree, env, metadata):
    fn = super().rewrite(tree, env, metadata)
    # do stuff with fn while having access to env, metadata
    return fn
```

**Comment by cdonovick** [comment]
@leonardt can we close this issue?
