### ISSUE TITLE
[RFC] Structure of passes

### ISSUE THREAD

**Issue by cdonovick** [leonardt/ast_tools#2]
Generally, decorators that manipulate the ast of a function or class should expect to receive an ast and env not a class or function.  Similarly, they should return the rewritten ast and env not the compiled function or class.
```
@compile
@rewrite_2
@rewrite_1
@get_ast_and_env
def function_to_be_rewritten(...): ...
``` 
We could have a base Pass that will automatically dump the AST after (or before) each  decorator when in debug mode.
```
@compile
# dumps AST to f'{./{debug_dir}/{function_file_name}/rewrite_2-{function_name}.py
@rewrite_2
# dumps AST to f'{./{debug_dir}/{function_file_name}/rewrite_1-{function_name}.py
@rewrite_1
# dumps initial AST to f'{./{debug_dir}/{function_file_name}/get_ast_and_env-{function_name}.py
@get_ast_and_env 
def function_to_be_rewritten(...): ...
```

**Comment by leonardt** [comment]
Seems like a good interface and enables the better composition and reuse of passes
