### ISSUE TITLE
AST rewrites do not retain original type annotations

### ISSUE THREAD

**Issue by rdaly525** [leonardt/ast_tools#26]
In the following ast rewrites the type annotations for 'Inst' is not retained

```
class PE(Peak):

  @end_rewrite()
  @if_to_phi(family.Bit.ite)
  @bool_to_bit()
  @ssa()
  @begin_rewrite()
  def __call__(self, inst: Inst):
    #...
```

**Comment by rdaly525** [comment]
I think an easy way to do this would be to save the annotations within begin_rewrite, then add the annotations back in during end_rewrite. This is unsafe if any arguments change during the rewrites, but this could be made explicit by passing a flag into `being_rewrite(keep_annotations=True)`

**Comment by cdonovick** [comment]
I can't replicate this issue.  Are you sure you aren't doing something weird inside of metaclass?  Also can you produce a test case that fails with only ast_tools dependencies? (No peak / hwtypes constructs)

**Comment by rdaly525** [comment]
Closing, as I cannot now reproduce either.
