### ISSUE TITLE
ssa pass is too conservative

### ISSUE THREAD

**Issue by rdaly525** [leonardt/ast_tools#27]
A common design pattern is to handle all the cases of an enum in the following way:

```
class Signed(Enum):
   signed=0
   unsigned=1

def sim(signed : Signed):
   if signed == Signed.signed:
       val = Bit(0)
   elif signed == Signed.unsigned:
       val = Bit(1)

   #rest of the code
```

The current ssa pass errors out due to not being able to prove that 'val' is set on all control paths. It would be great if the else was not necessary in this case, or to have something like `raise Unreachable()` in the else case.

We should also adhere to a common design pattern for both magma and peak for this very common case.

@cdonovick, @leonardt, it would be great to get your thoughts

**Comment by cdonovick** [comment]
I have no intentions on changing this.
Either set a default value before the if / elif or set one in an else.
