### ISSUE TITLE
Passes sometimes removes parenthesis, messing up operator precedence.

### ISSUE THREAD

**Issue by rdaly525** [leonardt/ast_tools#29]
In lassen there is a line of code that looks like:

`b = (Data(1) << (DATAWIDTH-1)) ^ b`

After running

```
@end_rewrite()
@if_to_phi(family.Bit.ite)
@bool_to_bit()
@ssa()
@beign_rewrite()

```
The generated function contains the line:

`b3 = Data(1) << DATAWIDTH - 1 ^ b2`

**Comment by cdonovick** [comment]
@rdaly525 can you provide a full test case that fails?

**Comment by cdonovick** [comment]
The case you provided is not broken.  https://docs.python.org/3.7/reference/expressions.html#operator-precedence

**Comment by rdaly525** [comment]
Yeah, I had a false assumption between the precedence of minus and xor...
