### ISSUE TITLE
Files in .ast_tools getting overwritten due to name aliasing

### ISSUE THREAD

**Issue by rdaly525** [leonardt/ast_tools#31]
If I utilize ast_tools passes on the `__call__` of two different classes, they will both try to generate a file with the same name `__call__.py`. This causes the second one to overwrite the file from the first one. Although this does not directly cause any issues, it is a pain for debugging, as error messages will be incorrect when errors occur in the first `__call__.py` file.

It would be great if we could do one of the following:
1) File names were generated with a uniqueness guarantee within a single python session
2) There was an easy way to pass a file name into the pass along with raising an error for name conflicts
3) When passes are run on class methods, use the name of the class + method instead of just the name of the method

**Comment by cdonovick** [comment]
I will add an argument to end_rewrite to allow a file name to be passed. I will also create a sentinel value "UNIQUE" or something similar which will guarantee a fresh name.

3 is impossible.  There is no way to tell if you are operating on a class method or a function.
