### ISSUE TITLE
Important warning issued?

### ISSUE THREAD

**Issue by rsetaluri** [leonardt/ast_tools#41]
I see the following line: https://github.com/leonardt/ast_tools/blob/854761fa9b14cb5c7ada684d423081e83299ff23/util/generate_ast/generate.py#L94

When I use ast_tools it seems to want 3.6, but I see that even this repo's travis expects 3.7 (https://github.com/leonardt/ast_tools/blob/854761fa9b14cb5c7ada684d423081e83299ff23/.travis.yml#L3). Should we just upgrade this to 3.7? Is there a better way to check for compatibility?

**Comment by leonardt** [comment]
I think it's because the latest release was built on 3.6, but I bumped the travis version afterwards.  We can do a new release with 3.7 compatibility.]

**Comment by rsetaluri** [comment]
That would be great - think most of the other tools have at least a weak dependence on 3.7 anyawy.

**Comment by leonardt** [comment]
New release is available, can you see if it removes the warning?

**Comment by rsetaluri** [comment]
Yup, gone! Thanks for addressing.
