### ISSUE TITLE
Regression in fault test suite

### ISSUE THREAD

**Issue by leonardt** [leonardt/ast_tools#79]
I'm not sure how important this is, but with the latest release the following example taken from fault doesn't work anymore with the SSA pass

```python

import magma as m
import fault


class MWrapperMeta(m.MagmaProtocolMeta):
    def __getitem__(cls, T):
        assert cls is MWrapper
        return type(cls)(f'MWrapper[{T}]', (cls,), {'_T_': T})

    def _to_magma_(cls):
        return cls._T_

    def _qualify_magma_(cls, d):
        return MWrapper[cls._T_.qualify(d)]

    def _flip_magma_(cls):
        return MWrapper[cls._T_.flip()]

    def _from_magma_value_(cls, value):
        return cls(value)


class MWrapper(m.MagmaProtocol, metaclass=MWrapperMeta):
    def __init__(self, val):
        if not isinstance(val, type(self)._T_):
            raise TypeError()
        self._value_ = val

    def _get_magma_value_(self):
        return self._value_

    def apply(self, f):
        return f(self._value_)


WrappedBits8 = MWrapper[m.UInt[8]]


@m.sequential2()
class Foo:
    def __call__(self, val: WrappedBits8) -> m.UInt[8]:
        return val.apply(lambda x: x + 1)


def test_proto():
    tester = fault.Tester(Foo)
    tester.circuit.val = 1
    tester.eval()
    tester.circuit.O.expect(2)
    tester.compile_and_run("verilator", flags=['-Wno-unused'])
```

It produces this error

```python
../ast_tools/ast_tools/passes/ssa.py:514: in leave_Assign
    assert not self._assigned_names, (to_module(original_node).code, self._assigned_names)
E   AssertionError: ('__0_return_0 = val.apply(lambda x: x + 1)', ['x_0'])
```

Upon investigation, it seems like the SSA pass is treating the `lambda x: x + 1` expression to contain an assignment (perhaps because the `x` inside the lambda parameter is treated as a "store").  Adding support for lambda (not sure whether it worked before or just missed this case) seems doable (we need to treat it as a store, but remove the assigned names after processing the lambda, so we use the new name for the parameters, but the correct SSA names for anything else coming from the outer scope).  Not sure if this is something we need though, so just documenting it here.

CC @cdonovick

**Comment by leonardt** [comment]
Also, this regression seems to have occurred between version 0.1.4 and 0.1.5, when we changed to FlattenSentinal and upgraded the libcst version (not sure if it's related to the FlattenSentinal stuff specifically or perhaps some change to libcst that causes the lambda to be visited differently)

**Comment by leonardt** [comment]
(As a workaround for fault, I just changed the lambda to be a function call and that seems to work fine)

**Comment by cdonovick** [comment]
Probably has to do with logic changes that came with getting the name table to work.

I remember that getting the assigned names to work right was bit of a pain.  Especially around params.

I think it can be fixed by incrementing/decrementing skip in `(visit|leave)_Parameters`

https://github.com/leonardt/ast_tools/blob/master/ast_tools/passes/ssa.py#L397-L399

https://github.com/leonardt/ast_tools/blob/master/ast_tools/passes/ssa.py#L528-L532

I can probably do this later tonight if you don't beat me to it.

**Comment by cdonovick** [comment]
Working on this now
