### ISSUE TITLE
Condition expressions are copied for phi nodes

### ISSUE THREAD

**Issue by leonardt** [leonardt/ast_tools#8]
Right now the ssa pass copies the condition to the input of each phi node (possibly problematic for magma because each expression creates a new instance, but a downstream compiler or magma itself could optimize this out). 

Alternatively, we could handle this in a subsequent pass by eliminating these common sub expressions (lift into a temporary), but this assumes that the expression has no side effects. However, since the expression only occurred once before the ssa pass, this is actually okay, since if it does have side effects, we in fact want the expression to only be executed once (as per the original code).

This brings up another issue, normally side effects don't occur for conditions that aren't executed in branches that are not traversed. In SSA form, all conditions will be executed.  Perhaps we want to limit this to only process side-effect free code? That would make things simpler.

A simpler, less general solution to the phi condition problem is to simply store the condition expression in a free name and use that as the input to the phis, but this doesn't address the above issue w.r.t. side effects in non-traversed branches.

**Comment by cdonovick** [comment]
Copying the conditions into a free a variable  seems reasonable and fairly straight forward.  

I think we have to limit our self to side effect free code. There's no getting around the fact that both branches are going to be run.

**Comment by leonardt** [comment]
I think this is done now with the condition names
