### ISSUE TITLE
Exec failing when transformed body refers to name in current (nested) scope

### ISSUE THREAD

**Issue by leonardt** [leonardt/ast_tools#9]
Here's the failing test (available in the branch `local-name-issue`)
```python
def test_exec_in_file():
    x = 3
    def foo():
        return x
    assert foo() == 3

    @end_rewrite()
    @begin_rewrite()
    def foo():
        return x

    assert foo() == 3
```

the test fails with

```
______________________________________________ test_exec_in_file _______________________________________________

    def test_exec_in_file():
        x = 3
        def foo():
            return x
        assert foo() == 3

        @end_rewrite()
        @begin_rewrite()
        def foo():
            return x

>       assert foo() == 3

tests/test_common.py:48:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def foo():
>       return x
E       NameError: name 'x' is not defined

.ast_tools/foo.py:2: NameError
====================================== 1 failed, 2 passed in 0.09 seconds ======================================
```

notice that the first invocation of `foo` (no rewrites) works okay.

I think this has to do with how locals/globals are treated in the context of the exec environment (not being the same as in a nested stack frame environment).

One way to work around the issue is to put everything in locals into globals, so I suspect it has to do with the variable lookup scheme in the exec environment being different than in the current definition context.

**Comment by leonardt** [comment]
Ah, got it, from the docs
> Remember that at module level, globals and locals are the same dictionary. If exec gets two separate objects as globals and locals, the code will be executed as if it were embedded in a class definition.

This code
```
class Foo:
    x = 3

    @staticmethod
    def foo():
        return x

assert Foo.foo() == 3
```

errors in the same way

```
Traceback (most recent call last):
  File "tests/test_common.py", line 58, in <module>
    assert Foo.foo() == 3
  File "tests/test_common.py", line 56, in foo
    return x
NameError: name 'x' is not defined
```

**Comment by leonardt** [comment]
Should we just combine globals and locals when execing the file?

**Comment by leonardt** [comment]
Relevant doc link: https://docs.python.org/3/library/functions.html#exec

**Comment by cdonovick** [comment]
Hmmm interesting I think we should be able to pass the `SymbolTable` as locals to exec and everything should work.

**Comment by leonardt** [comment]
From what I can tell, if you only pass one, you have to pass globals (which acts as locals) which also must be a dict (can't pass a MutableMapping)
